import { native } from "./native";

export const h1 = native("h1");
export const h2 = native("h2");
export const h3 = native("h3");
export const h4 = native("h4");
export const h5 = native("h5");
export const h6 = native("h6");
export const p = native("p");
export const div = native("div");
export const span = native("span");
export const button = native("button");
export const input = native("input");
export const select = native("select");
export const option = native("option");
export const textarea = native("textarea");
export const form = native("form");
export const label = native("label");
export const img = native("img");
export const ul = native("ul");
